name: Publish

on:
  push:
    branches: [main]

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-gh-pages:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.27.0

      - name: Setup node environment (for building)
        uses: actions/setup-node@v3
        with:
          node-version: 16.19
          cache: "pnpm"

      - name: Fetch dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Build project
        run: |
          pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
